version: '3'

services:
    monolith:
        image: node:14-alpine
        working_dir: /app
        volumes: 
            - /app/node_modules
            - ./:/app
        ports:
            - 3001:3000
        stdin_open: true